@ITS_URL = http://localhost:5288



GET  {{ITS_URL}}/api/User
Accept-Language: en-US,en;q=0.5


###

POST {{ITS_URL}}/api/Auth/register
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
  "username": "admin",
  "password": "1234",
  "email": "1234@example1.com",
  "isAdmin": "admin"
}


###


POST {{ITS_URL}}/api/Auth/login
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
  "email": "1234@example1.com",
  "password": "1234"
}

### Delete a user (Replace {id} with actual user ID)
DELETE  {{ITS_URL}}/api/User/11
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ1aW8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTcyODcwMTIzMSwiaXNzIjoieW91cl9pc3N1ZXJfaGVyZSIsImF1ZCI6InlvdXJfYXVkaWVuY2VfaGVyZSJ9.zrsYYQ9CkW35dCv49USzdeQWpaCbhmU2bj_nANkUlic