@ITS_URL = http://localhost:5288


### Get all cars
GET  {{ITS_URL}}/api/Car
Accept: application/json

###

### Get a car by ID (Replace {id} with actual car ID)
GET  {{ITS_URL}}/api/Car/1
Accept: application/json

###

### Create a new car
POST  {{ITS_URL}}/api/Car
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ1aW8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTcyODY5OTE0NSwiaXNzIjoieW91cl9pc3N1ZXJfaGVyZSIsImF1ZCI6InlvdXJfYXVkaWVuY2VfaGVyZSJ9.ZF3ijFDcQMr8DvsjtIQdIW2cMWgrLYr2l1VeFUPNG2o

{
  "carPlate": "ABC123",
  "url": "https://example.com/carimage.png",
  "userId": 5,
}

###

### Update an existing car (Replace {id} with actual car ID)
PUT  {{ITS_URL}}/api/Car/1
Content-Type: application/json

{
  "id": 1,
  "carPlate": "XYZ789",
  "url": "https://example.com/newcarimage.png",
  "userId": 3
}

###

### Delete a car (Replace {id} with actual car ID)
DELETE  {{ITS_URL}}/api/Car/4
Accept: application/json
