@ITS_URL = http://localhost:5288

@Authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMjYiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiIxQDEuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTcyOTE0MTg0NCwiaXNzIjoieW91cl9pc3N1ZXJfaGVyZSIsImF1ZCI6InlvdXJfYXVkaWVuY2VfaGVyZSJ9.Ja0R_0dJDqQqVWOm9dQ8HDDjch83dTAtriZ6U4auTGo

### Get all cars
GET  {{ITS_URL}}/api/Car
Accept: application/json

###

### Get a car by ID (Replace {id} with actual car ID)
GET  {{ITS_URL}}/api/Car/15
Accept: application/json

### Get a car list by page
GET {{ITS_URL}}/api/Car/allByPage?pageNumber=1&pageSize=3
Accept: application/json

### 获取当前用户相关的车辆列表 - 测试第一页
GET {{ITS_URL}}/api/Car/userCars?pageNumber=1&pageSize=5
Authorization: {{Authorization}}

###

### Create a new car
POST  {{ITS_URL}}/api/Car
Content-Type: application/json
Authorization: {{Authorization}}

{
  "carPlate": "ABC123",
  "url": "https://example.com/carimage.png",
  "userId": 22
}

###

### Update an existing car (Replace {id} with actual car ID)
PUT  {{ITS_URL}}/api/Car/27
Content-Type: application/json
Authorization: {{Authorization}}

{
  "id": 27,
  "carPlate": "XYZ789",
  "url": "https://example.com/newcarimage.png",
  "userId": 13
}

###

### Delete a car (Replace {id} with actual car ID)
DELETE  {{ITS_URL}}/api/Car/3
Accept: application/json
Authorization: {{Authorization}}



### Create a new car
POST  {{ITS_URL}}/api/Car/loginOrder
Content-Type: application/json
Authorization: {{Authorization}}

{
  "carPlate": "ABC56",
  "url": "https://example.com/carimage.png",
  "userId": 25
}
