@ITS_URL = http://localhost:5288

### Get all users
GET  {{ITS_URL}}/api/User
Accept: application/json

### Get a user list by page
GET {{ITS_URL}}/api/User/allByPage?pageNumber=1&pageSize=3
Accept: application/json

###

### Get a user by ID (Replace {id} with actual user ID)
GET  {{ITS_URL}}/api/User/1
Accept: application/json

###

### Create a new user
POST  {{ITS_URL}}/api/User
Content-Type: application/json

{
  "username": "user1",
  "password": "userpassword123",
  "email": "1@example1.com",
  "role": "user"
}

###

### Update an existing user (Replace {id} with actual user ID)
PUT  {{ITS_URL}}/api/User/1
Content-Type: application/json

{
  "id": 1, 
  "username": "johndoe_updated",
  "password": "newpassword123",
  "email": "johndoe_updated@example.com",
  "role": "user"
}

###

### Delete a user (Replace {id} with actual user ID)
DELETE  {{ITS_URL}}/api/User/8
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ1aW8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTcyODY5OTE0NSwiaXNzIjoieW91cl9pc3N1ZXJfaGVyZSIsImF1ZCI6InlvdXJfYXVkaWVuY2VfaGVyZSJ9.ZF3ijFDcQMr8DvsjtIQdIW2cMWgrLYr2l1VeFUPNG2o
