import type { Metadata } from 'next';
import { headers } from 'next/headers';
import localFont from 'next/font/local';
import './globals.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import Link from 'next/link';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const host = headersList.get('host');
  const currentURL = headersList.get('referer') || '';
  let isLoginOrRegister = false;

  // Extract the pathname from the referer or URL
  if (currentURL) {
    const url = new URL(currentURL);
    const pathname = url.pathname; // This will give you the current pathname
    isLoginOrRegister = pathname === '/login' || pathname === '/register';
  }

  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}>
        <div className='flex h-full'>
          {isLoginOrRegister ? (
            <section className='flex-1 p-10'>{children}</section>
          ) : (
            <>
              {/* Left-side Menu */}
              <nav>
                <div className='w-60 h-[100vh] bg-gray-200 p-5 border-r border-gray-300 '>
                  <ul className='space-y-4'>
                    <li>
                      <Link href='/plate'>Car Plate</Link>
                    </li>
                    <li>
                      <Link href='/order'>Order</Link>
                    </li>
                    <li>
                      <Link href='/dashboard'>Dashboard</Link>
                    </li>
                  </ul>
                </div>
              </nav>
              {/* Main Content */}
              <main>
                <div className='flex-1 p-10'>{children}</div>
              </main>
            </>
          )}
        </div>
      </body>
    </html>
  );
}
